name: Google To GeoJSON

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  download_and_convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
  
    - name: Install required Python packages
      run: |
        python -m pip install --upgrade pip
        pip install shapely requests

    - name: Download KMZ file
      run: |
        URL="https://www.google.com/maps/d/kml?mid=1GkDHfCOTV4oes0EMZGx1CeLOrLS6-hc&cid=mp&cv=5EpEEGy2YmA.zh_CN"
        OUTPUT_FILE="downloaded_file.kmz"
        curl -o $OUTPUT_FILE $URL
      shell: bash

    - name: Convert KMZ to GeoJSON
      run: |
        mkdir -p data
        python convert_kmz_to_geojson.py downloaded_file.kmz data/geo.json
      shell: bash

    - name: Commit and push converted GeoJSON
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add data/geo.json
        git diff --quiet && git diff --staged --quiet || (git commit -m 'Automated commit of converted GeoJSON' && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.GHP_TOKEN }}
