name: Daily API Data Backup

on:
  schedule:
    # 每天 UTC 时间 00:00 执行
    - cron: '0 0 * * *'

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Get API data
        run: |
          curl -o data.json https://memos.hsinyau.cc/api/v1/memo?openId=${{ secrets.OPEN_ID }}

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Daily backup'
          commit_options: '--author "GitHub Actions <actions@github.com>"'
          commit_files: |
            data.json
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GHP_TOKEN }}
