name: 'Memos Backup Bot'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0,12 * * *'

jobs:
  fetch_data:
    name: fetch data
    runs-on: ubuntu-latest
    env:
      OPEN_ID: ${{ secrets.OPEN_ID }}
      GITHUB_TOKEN: ${{ secrets.GHP_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install axios

      - name: Build
        run: node index.js

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Daily API data update'
          commit_options: '--author "GitHub Actions <actions@github.com>"'
          commit_files: |
            data.json
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com

