name: 'Memos Backup Bot'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0,12 * * *'

jobs:
  fetch_data:
    name: fetch data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install axios

      - name: Build
        run: node index.js
        env:
          OPEN_ID: ${{ secrets.OPEN_ID }}

      - name: commit
        run: |
          git config --global user.email `${{ AC_MAIL }}`
          git config --global user.name `${{ AC_USER }}`
          git add .
          git commit -m "update" -a
        
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GHP_TOKEN }}

