name: Sync Data to Cloudflare R2

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  rclone:
    name: s3 bucket Sync 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: '2'

    - name: Setup Rclone
      uses: AnimMouse/setup-rclone@v1
      with:
        rclone_config: ${{ secrets.RCLONE_CONFIG }}

    - name: Rclone Sync
      run: |
        # 列出两个 commit 之间变化的文件
        changed_files=$(git diff --name-only HEAD~1 HEAD)

        # 列出被删除的文件
        deleted_files=$(git diff --name-only --diff-filter=D HEAD~1 HEAD)

        # 过滤出指定文件夹的文件
        # 只保留 emoji、footprints、moments、neodb、vsco 文件夹下的文件
        filtered_changed_files=""
        filtered_deleted_files=""

        # 处理变化的文件
        while IFS= read -r file; do
          if [[ -n "$file" ]]; then
            # 检查文件是否在指定文件夹中
            if [[ "$file" =~ ^(emoji|footprints|moments|neodb|vsco)/ ]]; then
              filtered_changed_files="$filtered_changed_files$file"$'\n'
            fi
          fi
        done <<< "$changed_files"

        # 处理删除的文件
        while IFS= read -r file; do
          if [[ -n "$file" ]]; then
            # 检查文件是否在指定文件夹中
            if [[ "$file" =~ ^(emoji|footprints|moments|neodb|vsco)/ ]]; then
              filtered_deleted_files="$filtered_deleted_files$file"$'\n'
            fi
          fi
        done <<< "$deleted_files"

        # 使用 rclone 同步这些文件
        echo "$filtered_changed_files" > changed_files.txt
        echo "$filtered_deleted_files" > deleted_files.txt

        # 删除空行
        sed -i '/^$/d' changed_files.txt
        sed -i '/^$/d' deleted_files.txt

        # 使用 rclone 同步这些文件
        if [ -s changed_files.txt ]; then
          rclone sync . Cloudflare:${{ secrets.CF_R2_BUCKET }} --include-from changed_files.txt || true
          echo "Changed Files:"
          cat changed_files.txt
        else
          echo "No changed files in specified folders"
        fi

        if [ -s deleted_files.txt ]; then
          rclone delete Cloudflare:${{ secrets.CF_R2_BUCKET }} --include-from deleted_files.txt || true
          echo "Deleted Files:"
          cat deleted_files.txt
        else
          echo "No deleted files in specified folders"
        fi
