name: Sync Data to Cloudflare R2

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  rclone:
    name: s3 bucket Sync 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: '2'

    - name: Setup Rclone
      uses: AnimMouse/setup-rclone@v1
      with:
        rclone_config: ${{ secrets.RCLONE_CONFIG }}

    - name: Rclone Sync
      run: |
        echo "=== Debug: Current directory ==="
        pwd
        echo "=== Debug: Git status ==="
        git status --porcelain
        echo "=== Debug: Git log (last 3 commits) ==="
        git log --oneline -3
        
        # 检查是否有足够的历史记录
        if git rev-parse HEAD~1 >/dev/null 2>&1; then
          echo "=== Debug: Found previous commit HEAD~1 ==="
          
          # 列出两个 commit 之间变化的文件
          changed_files=$(git diff --name-only HEAD~1 HEAD)
          deleted_files=$(git diff --name-only --diff-filter=D HEAD~1 HEAD)
          
          echo "=== Debug: All changed files ==="
          echo "$changed_files"
          echo "=== Debug: All deleted files ==="
          echo "$deleted_files"
          
          # 过滤出指定文件夹的文件
          # 只保留 emoji、footprints、moments、neodb、vsco 文件夹下的文件
          filtered_changed_files=""
          filtered_deleted_files=""
          
          # 处理变化的文件
          echo "=== Debug: Processing changed files ==="
          while IFS= read -r file; do
            if [[ -n "$file" ]]; then
              echo "Processing: $file"
              # 检查文件是否在指定文件夹中
              if [[ "$file" =~ ^(emoji|footprints|moments|neodb|vsco)/ ]]; then
                filtered_changed_files="$filtered_changed_files$file"$'\n'
                echo "  -> MATCHED: $file"
              else
                echo "  -> SKIPPED: $file"
              fi
            fi
          done <<< "$changed_files"
          
          # 处理删除的文件
          echo "=== Debug: Processing deleted files ==="
          while IFS= read -r file; do
            if [[ -n "$file" ]]; then
              echo "Processing: $file"
              # 检查文件是否在指定文件夹中
              if [[ "$file" =~ ^(emoji|footprints|moments|neodb|vsco)/ ]]; then
                filtered_deleted_files="$filtered_deleted_files$file"$'\n'
                echo "  -> MATCHED: $file"
              else
                echo "  -> SKIPPED: $file"
              fi
            fi
          done <<< "$deleted_files"
          
          # 使用 rclone 同步这些文件
          echo "$filtered_changed_files" > changed_files.txt
          echo "$filtered_deleted_files" > deleted_files.txt
          
          # 删除空行
          sed -i '/^$/d' changed_files.txt
          sed -i '/^$/d' deleted_files.txt
          
          echo "=== Debug: Final changed_files.txt ==="
          if [ -s changed_files.txt ]; then
            cat changed_files.txt
          else
            echo "(empty)"
          fi
          
          echo "=== Debug: Final deleted_files.txt ==="
          if [ -s deleted_files.txt ]; then
            cat deleted_files.txt
          else
            echo "(empty)"
          fi
          
          # 使用 rclone 同步这些文件
          if [ -s changed_files.txt ]; then
            echo "=== Syncing changed files ==="
            rclone sync . Cloudflare:${{ secrets.CF_R2_BUCKET }} --include-from changed_files.txt --verbose || true
            echo "Changed Files:"
            cat changed_files.txt
          else
            echo "No changed files in specified folders"
          fi
          
          if [ -s deleted_files.txt ]; then
            echo "=== Deleting files ==="
            rclone delete Cloudflare:${{ secrets.CF_R2_BUCKET }} --include-from deleted_files.txt --verbose || true
            echo "Deleted Files:"
            cat deleted_files.txt
          else
            echo "No deleted files in specified folders"
          fi
        else
          echo "=== No previous commit found, syncing all files ==="
          rclone sync . Cloudflare:${{ secrets.CF_R2_BUCKET }} --verbose || true
          echo "Synced all files"
        fi

    - name: Sync All Specified Folders
      run: |
        echo "=== Syncing all files from specified folders to ensure completeness ==="
        
        # 创建包含所有指定文件夹文件的列表
        echo "Creating file list for specified folders..."
        
        # 使用 find 命令找到所有指定文件夹下的文件
        find emoji footprints moments neodb vsco -type f 2>/dev/null > all_specified_files.txt || true
        
        echo "=== All files in specified folders ==="
        if [ -s all_specified_files.txt ]; then
          cat all_specified_files.txt
          echo "Total files: $(wc -l < all_specified_files.txt)"
        else
          echo "No files found in specified folders"
        fi
        
        # 同步所有指定文件夹的文件到 R2
        if [ -s all_specified_files.txt ]; then
          echo "=== Syncing all specified folder files to R2 ==="
          rclone sync . Cloudflare:${{ secrets.CF_R2_BUCKET }} --include-from all_specified_files.txt --verbose || true
          echo "Completed syncing all specified folder files"
        else
          echo "No files to sync from specified folders"
        fi
